spring.application.name=cms
server.port=${PORT:8080}
# ========== DATASOURCE ==========

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d662jsfpm1nc73b433k0-a.oregon-postgres.render.com:5432/config_services
spring.datasource.username='db username'
spring.datasource.password='you db password'
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# server.forward-headers-strategy=framework
